######################################################################
# Automatically generated by qmake (2.01a) mi� oct 1 17:55:16 2014
######################################################################

TEMPLATE = app
TARGET = qmb
OBJECTS_DIR = build
MOC_DIR = build
RCC_DIR = build

greaterThan(QT_MAJOR_VERSION, 4) {
   QT += widgets
}

DEPENDPATH += . \
              include \
              resources \
              src \
              include/persistence \
              include/view \
              src/persistence \
              src/view

INCLUDEPATH += . include/persistence include/view include

# Input
HEADERS += include/global.h \
           include/persistence/persistencemanager.h \
           include/view/centralwidget.h \
           include/view/mainwindow.h \
           include/view/mibtreemodel.h \
           include/view/mibtreeproxymodel.h \
           include/view/oideditordialog.h \
           include/view/optionsdialog.h \
           include/view/propertiesdialog.h

SOURCES += src/main.cpp \
           src/persistence/persistencemanager.cpp \
           src/view/centralwidget.cpp \
           src/view/mainwindow.cpp \
           src/view/mibtreemodel.cpp \
           src/view/mibtreeproxymodel.cpp \
           src/view/oideditordialog.cpp \
           src/view/optionsdialog.cpp \
           src/view/propertiesdialog.cpp

LIBS += -lqt-net-snmp

RESOURCES += resources/qmb.qrc

OTHER_FILES += \
    README \
    LICENSE \
    AUTHOR \
    THANKS \
    INSTALL \
    COPYRIGHT \
    CHANGELOG

message("Qt Version: $$QT_VERSION")
